/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorshipIndexRouteImport } from './routes/mentorship/index'
import { Route as MentorshipApplyIndexRouteImport } from './routes/mentorship/apply/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipIndexRoute = MentorshipIndexRouteImport.update({
  id: '/mentorship/',
  path: '/mentorship/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipApplyIndexRoute = MentorshipApplyIndexRouteImport.update({
  id: '/mentorship/apply/',
  path: '/mentorship/apply/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mentorship/': typeof MentorshipIndexRoute
  '/mentorship/apply/': typeof MentorshipApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentorship': typeof MentorshipIndexRoute
  '/mentorship/apply': typeof MentorshipApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mentorship/': typeof MentorshipIndexRoute
  '/mentorship/apply/': typeof MentorshipApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mentorship/' | '/mentorship/apply/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mentorship' | '/mentorship/apply'
  id: '__root__' | '/' | '/mentorship/' | '/mentorship/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MentorshipIndexRoute: typeof MentorshipIndexRoute
  MentorshipApplyIndexRoute: typeof MentorshipApplyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/': {
      id: '/mentorship/'
      path: '/mentorship'
      fullPath: '/mentorship/'
      preLoaderRoute: typeof MentorshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/apply/': {
      id: '/mentorship/apply/'
      path: '/mentorship/apply'
      fullPath: '/mentorship/apply/'
      preLoaderRoute: typeof MentorshipApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MentorshipIndexRoute: MentorshipIndexRoute,
  MentorshipApplyIndexRoute: MentorshipApplyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
