/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PocketsFullTradingMentorshipRouteImport } from './routes/pockets-full-trading-mentorship'
import { Route as IndexRouteImport } from './routes/index'

const PocketsFullTradingMentorshipRoute =
  PocketsFullTradingMentorshipRouteImport.update({
    id: '/pockets-full-trading-mentorship',
    path: '/pockets-full-trading-mentorship',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pockets-full-trading-mentorship': typeof PocketsFullTradingMentorshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pockets-full-trading-mentorship': typeof PocketsFullTradingMentorshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pockets-full-trading-mentorship': typeof PocketsFullTradingMentorshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pockets-full-trading-mentorship'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pockets-full-trading-mentorship'
  id: '__root__' | '/' | '/pockets-full-trading-mentorship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PocketsFullTradingMentorshipRoute: typeof PocketsFullTradingMentorshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pockets-full-trading-mentorship': {
      id: '/pockets-full-trading-mentorship'
      path: '/pockets-full-trading-mentorship'
      fullPath: '/pockets-full-trading-mentorship'
      preLoaderRoute: typeof PocketsFullTradingMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PocketsFullTradingMentorshipRoute: PocketsFullTradingMentorshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
